apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "akslochen"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "akslochen"
    spec:
      containers:
        - name: "akslochen"
          image: "aether2acr.azurecr.io/akslochen"
          ports:
          - containerPort: 8088