apiVersion: v1
kind: Service
metadata:
    name: "akslochen"
    labels:
        app: "akslochen"
spec:
    type: LoadBalancer
    ports:
    - port: 8088
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "akslochen"